-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 09:45:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AwesomeCasino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AwesomeCasino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AwesomeCasino` ;
USE `AwesomeCasino` ;

-- -----------------------------------------------------
-- Table `AwesomeCasino`.`GameTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AwesomeCasino`.`GameTypes` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AwesomeCasino`.`Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AwesomeCasino`.`Games` (
  `ID` INT NOT NULL,
  `Game` VARCHAR(45) NULL,
  `Type_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Game_Type_FK_idx` (`Type_ID` ASC) VISIBLE,
  CONSTRAINT `Game_Type_FK`
    FOREIGN KEY (`Type_ID`)
    REFERENCES `AwesomeCasino`.`GameTypes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AwesomeCasino`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AwesomeCasino`.`Countries` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AwesomeCasino`.`GameCountries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AwesomeCasino`.`GameCountries` (
  `Game_ID` INT NOT NULL,
  `Country_ID` INT NOT NULL,
  PRIMARY KEY (`Game_ID`, `Country_ID`),
  INDEX `Country_ID_FK_idx` (`Country_ID` ASC) VISIBLE,
  CONSTRAINT `Country_ID_FK`
    FOREIGN KEY (`Country_ID`)
    REFERENCES `AwesomeCasino`.`Countries` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Game_ID_FK`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `AwesomeCasino`.`Games` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AwesomeCasino`.`Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AwesomeCasino`.`Players` (
  `ID` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Country_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `COUNTRY_ID_FK_idx` (`Country_ID` ASC) VISIBLE,
  CONSTRAINT `COUNTRY_ID_FK`
    FOREIGN KEY (`Country_ID`)
    REFERENCES `AwesomeCasino`.`Countries` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AwesomeCasino`.`PlayersFavouriteGames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AwesomeCasino`.`PlayersFavouriteGames` (
  `Player_ID` INT NOT NULL,
  `Game_ID` INT NOT NULL,
  PRIMARY KEY (`Player_ID`, `Game_ID`),
  INDEX `Game_ID_FK_idx` (`Game_ID` ASC) VISIBLE,
  CONSTRAINT `Player_ID_FK`
    FOREIGN KEY (`Player_ID`)
    REFERENCES `AwesomeCasino`.`Players` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Game_ID_FK`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `AwesomeCasino`.`Games` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AwesomeCasino`.`PlayerSpins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AwesomeCasino`.`PlayerSpins` (
  `ID` INT NOT NULL,
  `Timestamp` VARCHAR(45) NOT NULL,
  `Player_ID` INT NOT NULL,
  `Game_ID` INT NOT NULL,
  `Payout` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Player_ID_FK_idx` (`Player_ID` ASC) VISIBLE,
  INDEX `Game_ID_FK_idx` (`Game_ID` ASC) VISIBLE,
  CONSTRAINT `Player_ID_FK`
    FOREIGN KEY (`Player_ID`)
    REFERENCES `AwesomeCasino`.`Players` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Game_ID_FK`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `AwesomeCasino`.`Games` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
